In [47]:
import pandas as pd

In [48]:
data=pd.read_excel(r"C:\Users\Ravi\OneDrive\Desktop\E-commerce_Sales\Ecommerce_Sales_Data_2024_2025.xlsx")

In [49]:
data.head()

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode
0,14056,2023-10-04,Hazel Sinha,East,Guwahati,Home Decor,Vase,Vase Vitae,3,7716,20,18518.4,2273.75,COD
1,13340,2023-10-04,Badal Mand,South,Hyderabad,Kitchen,Mixer Grinder,Mixer Grinder Quod,1,39026,0,39026.0,6959.45,COD
2,12670,2023-10-04,Dhruv Chakrabarti,West,Surat,Groceries,Sugar,Sugar Non,1,61466,0,61466.0,11022.91,COD
3,12243,2023-10-04,Ela Jain,South,Chennai,Sports,Yoga Mat,Yoga Mat Ab,3,18949,0,56847.0,4259.92,Credit Card
4,11534,2023-10-04,Advik Sarraf,West,Surat,Furniture,Bed,Bed Sapiente,5,44511,20,178044.0,41209.73,COD

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   datetime64[ns]
 2   Customer Name  5000 non-null   object
 3   Region         5000 non-null   object
 4   City           5000 non-null   object
 5   Category       5000 non-null   object
 6   Sub-Category   5000 non-null   object
 7   Product Name   5000 non-null   object
 8   Quantity       5000 non-null   int64
 9   Unit Price     5000 non-null   int64
 10  Discount       5000 non-null   int64
 11  Sales          5000 non-null   float64
 12  Profit         5000 non-null   float64
 13  Payment Mode   5000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 547.0+ KB

In [51]:
data.describe(include="all")

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode
count,5000.000000,5000,5000,5000,5000,5000,5000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000
unique,NaN,NaN,4844,4,20,10,50,3835,NaN,NaN,NaN,NaN,NaN,5
top,NaN,NaN,Vritika Cherian,North,Guwahati,Kitchen,Sofa,Chair Adipisci,NaN,NaN,NaN,NaN,NaN,Net Banking
freq,NaN,NaN,3,1288,293,528,122,5,NaN,NaN,NaN,NaN,NaN,1010
mean,12500.500000,2024-09-30 18:58:27.840000,NaN,NaN,NaN,NaN,NaN,NaN,2.992600,39760.904600,10.051000,106733.204870,15941.746982,NaN
min,10001.000000,2023-10-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,222.000000,0.000000,264.100000,19.120000,NaN
25%,11250.750000,2024-04-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,20312.250000,5.000000,39766.537500,4892.295000,NaN
50%,12500.500000,2024-09-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,39459.500000,10.000000,83080.325000,11108.525000,NaN
75%,13750.250000,2025-03-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,59721.750000,15.000000,156968.587500,22467.987500,NaN
max,15000.000000,2025-10-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,79998.000000,20.000000,398485.000000,89688.440000,NaN
std,1443.520003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.413133,22831.783946,7.084662,85108.208202,14897.684916,NaN

In [52]:
data.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit Price       0
Discount         0
Sales            0
Profit           0
Payment Mode     0
dtype: int64

In [53]:
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(' ','_')

In [54]:
data.head(2)

,order_id,order_date,customer_name,region,city,category,sub-category,product_name,quantity,unit_price,discount,sales,profit,payment_mode
0,14056,2023-10-04,Hazel Sinha,East,Guwahati,Home Decor,Vase,Vase Vitae,3,7716,20,18518.4,2273.75,COD
1,13340,2023-10-04,Badal Mand,South,Hyderabad,Kitchen,Mixer Grinder,Mixer Grinder Quod,1,39026,0,39026.0,6959.45,COD

In [55]:
# 1. Total Sales and Profit by Region

region_stats = data.groupby('region')[['sales', 'profit']].sum().sort_values(by='sales', ascending=False)
print(region_stats)

               sales       profit
region
North   1.435782e+08  21343004.33
East    1.358116e+08  20532558.12
West    1.310460e+08  19580123.14
South   1.232302e+08  18253049.32

In [56]:
# 2. Top Performing Categories

top_categories = data.groupby('category')[['profit']].sum().sort_values(by='profit', ascending=False).head(5)
print(top_categories)

                 profit
category
Furniture    8693087.03
Home Decor   8556846.94
Clothing     8445750.29
Books        8076273.29
Electronics  8042133.88

In [57]:
top_cities = data.groupby('city')['sales'].sum().sort_values(ascending=False).head(5)
print(top_cities)

city
Bangalore     29989840.85
Lucknow       29901483.40
Guwahati      29606888.90
Chandigarh    29331057.35
Jaipur        29319402.90
Name: sales, dtype: float64

In [58]:
# 4. Correlation between Discount and Profit

discount_profit_corr = data['discount'].corr(data['profit'])
print(discount_profit_corr)

-0.08851620188980268

In [59]:
# 5. Preferred Payment Modes

payment_counts = data['payment_mode'].value_counts()
print(payment_counts)

payment_mode
Net Banking    1010
COD            1005
Debit Card     1003
Credit Card     994
UPI             988
Name: count, dtype: int64

In [60]:
# 6. Top 5 Cities by Sales

top_cities = data.groupby('city')['sales'].sum().sort_values(ascending=False).head(5)
print(top_cities)

city
Bangalore     29989840.85
Lucknow       29901483.40
Guwahati      29606888.90
Chandigarh    29331057.35
Jaipur        29319402.90
Name: sales, dtype: float64

In [61]:
data.to_csv("Ecommerce_Sales_Analysis.csv", index=False)

In [62]:
print(data.columns)
print(data.shape)

Index(['order_id', 'order_date', 'customer_name', 'region', 'city', 'category',
       'sub-category', 'product_name', 'quantity', 'unit_price', 'discount',
       'sales', 'profit', 'payment_mode'],
      dtype='object')
(5000, 14)